server:
  port: 8888
spring:
  profiles:
    active: native

---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/java/cloud/profile/{application}/{profile}
---
spring:
  profiles: git
  cloud:
    server:
      git:
        uri: https://github.com/amgalan-sp/profile/
        search-paths:
          - "book-service/{application}/{profile}"
